---
abstract: 'Methods to format, count, sanitize, etc...'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-MoreUtilHelpers
no_index:
  directory:
    - t
    - inc
requires:
  Lingua::EN::Inflect: '0'
  Mojolicious: '4.80'
resources:
  bugtracker: http://github.com/sshaw/Mojolicious-Plugin-MoreUtilHelpers/issues
  repository: http://github.com/sshaw/Mojolicious-Plugin-MoreUtilHelpers
version: '0.03'
